services:
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - netapp
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=721
    ports:
      - 5432:5432
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - netapp
  redis:
    image: redis
    ports:
      - 4571:6379
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
networks:
  netapp: