services:
  app:
    build: .
    ports:
      - 8888:8888
    networks:
      - netapp
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=721
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - netapp
  redis:
    image: redis
    ports:
      - 4571:6379
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
networks:
  netapp: